export class Monsters {
    slug: string;
    name: string;
    size: string;
    type: string;
    subtype: string;
    group: string;
    alignment: string;
    armor_class: number;
    armor_desc: string;
    hit_points: number;
    hit_dice: string;
    speed: object;
    strength: number;
    dexterity: number;
    constitution: number;
    intelligence: number;
    wisdom: number;
    charisma: number;
    strength_save: string;
    dexterity_save: string;
    constitution_save: string;
    intelligence_save: string;
    wisdom_save: string;
    charisma_save: string;
    perception: number; //need to check if correct 
    skills: object;
    damage_vulnerabilities: string;
    damage_resistances: string;
    damage_immunities: string;
    condition_immunities: string;
    senses: string;
    languages: string;
    challenge_rating: number;
    actions: object[];
    reactions: string;
    legendary_desc: string;
    legendary_actions: object[];
    special_abilities: object[];
    spell_list: string[];

    constructor(monsterObj){
        this.slug = monsterObj.slug;
        this.name = monsterObj.name;
        this.size = monsterObj.size;
        this.type = monsterObj.type;
        this.subtype = monsterObj.subtype;
        this.group = monsterObj.group;
        this.alignment = monsterObj.alignment;
        this.armor_class = monsterObj.armor_class;
        this.armor_desc = monsterObj.armor_desc;
        this.hit_points = monsterObj.hit_points;
        this.hit_dice = monsterObj.hit_dice;
        this.speed = monsterObj.speed;
        this.strength = monsterObj.strength;
        this.dexterity = monsterObj.dexterity;
        this.constitution = monsterObj.constitution;
        this.intelligence = monsterObj.intelligence;
        this.wisdom = monsterObj.wisdom;
        this.charisma = monsterObj.charisma;
        this.strength_save = monsterObj.strength_save;
        this.dexterity_save = monsterObj.dexterity_save;
        this.constitution_save = monsterObj.constitution_save;
        this.intelligence_save = monsterObj.intelligence_save;
        this.wisdom_save = monsterObj.wisdom_save;
        this.charisma_save = monsterObj.charisma_save;
        this.perception = monsterObj.perception;
        this.skills = monsterObj.skills;
        this.damage_vulnerabilities = monsterObj.damage_vulnerabilities;
        this.damage_resistances = monsterObj.damage_resistances;
        this.damage_immunities = monsterObj.damage_immunities;
        this.condition_immunities = monsterObj.condition_immunities;
        this.senses = monsterObj.senses;
        this.languages = monsterObj.languages;
        this.challenge_rating = monsterObj.challenge_rating;
        this.actions = monsterObj.actions;
        this.reactions = monsterObj.reactions;
        this.legendary_desc = monsterObj.legendary_desc;
        this.legendary_actions = monsterObj.legendary_actions;
        this.special_abilities = monsterObj.special_abilities;
        this.spell_list = monsterObj.spell_list;
    }
}
