export class CharacterSheet {
    constructor(
        public uid: string ='',
        public charname:string='',
        public classlevel:string='',
        public background:string='',
        public playername:string='',
        public features:string='',
        public equipment:string='',
        public flaws:string='',
        public personality:string='',
        public bonds:string='',
        public ideals:string='',
        public race:string='',
        public otherprofs:string='',
        public alignment:string='',
        public experiencepoints:number=0,
        public Strengthscore:number=0,
        public Strengthmod:string='',
        public DexterityScore:number=0,
        public Dexteritymod:string='',
        public Constitutionscore:number=0,
        public Constitutionmod:string='',
        public Wisdomscore:number=0,
        public Wisdommod:string='',
        public Intelligencescore:number=0,
        public Intelligencemod:string='',
        public Charismascore:number=0,
        public Charismamod:string='',
        public proficiencybonus:string='',
        public Strengthsave:string='',
        public Dexteritysave:string='',
        public Constitutionsave:string='',
        public Wisdomsave:string='',
        public Intelligencesave:string='',
        public Charismasave:string='',
        public Acrobatics:string='',
        public Animalhandling:string='',
        public Arcana:string='',
        public Athletics:string='',
        public Deception:string='',
        public History:string='',
        public Insight:string='',
        public Intimidation:string='',
        public Investigation:string='',
        public Medicine:string='',
        public Nature:string='',
        public Perception:string='',
        public Performance:string='',
        public Persuasion:string='',
        public Religion:string='',
        public Sleightofhand:string='',
        public Stealth:string='',
        public Survival:string='',
        public PassivePerception:number=null,
        public ac:number=null,
        public Initiative:string='',
        public speed:number=null,
        public maxHP:number=null,
        public currentHP:number=null,
        public tempHP:number=null,
        public totalHD:string='',
        public remainingHD:string='',
        public atkname1:string='',
        public atkbonus1:string='',
        public atkdamage1:string='',
        public atkname2:string='',
        public atkbonus2:string='',
        public atkdamage2:string='',
        public atkname3:string='',
        public atkbonus3:string='',
        public atkdamage3:string='',
        public sp:number=null,
        public pp:number=null,
        public gp:number=null,
        public ep:number=null,
        public cp:number=null,
        public inspiration:boolean=false,
        public medicineprof:boolean=false,
        public natureprof:boolean=false,
        public perceptionprof:boolean=false,
        public performanceprof:boolean=false,
        public persuasionprof:boolean=false,
        public sleightofhandprof:boolean=false,
        public religionprof:boolean=false,
        public stealthprof:boolean=false,
        public survivalprof:boolean=false,
        public deathsuccess1:boolean=false,
        public deathsuccess2:boolean=false,
        public deathsuccess3:boolean=false,
        public deathfail1:boolean=false,
        public deathfail2:boolean=false,
        public deathfail3:boolean=false,
        public strengthsaveprof:boolean=false,
        public dexteritysaveprof:boolean=false,
        public charismasaveprof:boolean=false,
        public intelligencesaveprof:boolean=false,
        public constitutionsaveprof:boolean=false,
        public wisdomsaveprof:boolean=false,
        public acrobaticsprof:boolean=false,
        public athleticsprof:boolean=false,
        public animalhandlingprof:boolean=false,
        public arcanaprof:boolean=false,
        public deceptionprof:boolean=false,
        public historyprof:boolean=false,
        public insightprof:boolean=false,
        public intimidationprof:boolean=false,
        public investigationprof:boolean=false,
      ){}
















    
}